root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - simple-import-sort
  - prettier
  - unused-imports
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/typescript'
  - 'plugin:import/recommended'
  - prettier
rules:
  no-throw-literal: error
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  unused-imports/no-unused-imports: error
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/prefer-namespace-keyword': off
  '@typescript-eslint/consistent-type-imports': warn
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
globals:
  # Globals for jest-puppeteer
  page: true
  browser: true
  context: true
  jestPuppeteer: true
